package reporter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sandgardenhq/find-the-gaps/internal/analyzer"
	"github.com/sandgardenhq/find-the-gaps/internal/docholiday"
)

// WritePrompts renders the Doc Holiday prompts to prompts.md in dir.
func WritePrompts(dir string, prompts []docholiday.Prompt) error {
	return os.WriteFile(filepath.Join(dir, "prompts.md"), BuildPromptsBytes(prompts), 0o644)
}

// BuildPromptsBytes renders prompts.md: a preamble, then a "Fix Stale
// Documentation" section and a "Document New Features" section, each bucketed
// Large→Medium→Small. Empty buckets are omitted; an empty section renders
// "_None found._".
func BuildPromptsBytes(prompts []docholiday.Prompt) []byte {
	var sb strings.Builder
	sb.WriteString("# Doc Holiday Prompts\n\n")
	sb.WriteString("_Generated by Find the Gaps. Paste any block into Doc Holiday (https://doc.holiday)._\n\n")

	writePromptCategory(&sb, "Fix Stale Documentation", prompts, docholiday.CategoryStale)
	writePromptCategory(&sb, "Document New Features", prompts, docholiday.CategoryMissing)

	return []byte(sb.String())
}

func writePromptCategory(sb *strings.Builder, title string, prompts []docholiday.Prompt, cat docholiday.Category) {
	fmt.Fprintf(sb, "## %s\n\n", title)
	var any bool
	for _, p := range []analyzer.Priority{analyzer.PriorityLarge, analyzer.PriorityMedium, analyzer.PrioritySmall} {
		bucket := filterPromptsByCatPriority(prompts, cat, p)
		if len(bucket) == 0 {
			continue
		}
		any = true
		fmt.Fprintf(sb, "### %s\n\n", priorityHeading(p))
		for _, pr := range bucket {
			fmt.Fprintf(sb, "#### %s\n\n", pr.Heading)
			if pr.Note != "" {
				fmt.Fprintf(sb, "_%s_\n\n", pr.Note)
			}
			fence := fenceFor(pr.Body)
			fmt.Fprintf(sb, "%s\n%s\n%s\n\n", fence, pr.Body, fence)
		}
	}
	if !any {
		sb.WriteString("_None found._\n\n")
	}
}

func filterPromptsByCatPriority(prompts []docholiday.Prompt, cat docholiday.Category, p analyzer.Priority) []docholiday.Prompt {
	var out []docholiday.Prompt
	for _, pr := range prompts {
		if pr.Category == cat && pr.Priority == p {
			out = append(out, pr)
		}
	}
	return out
}

// fenceFor returns a backtick fence at least one tick longer than the longest
// run of backticks inside body, so a body containing ``` stays a valid block.
func fenceFor(body string) string {
	longest, run := 0, 0
	for _, r := range body {
		if r == '`' {
			run++
			if run > longest {
				longest = run
			}
		} else {
			run = 0
		}
	}
	n := 3
	if longest+1 > n {
		n = longest + 1
	}
	return strings.Repeat("`", n)
}
