#!/usr/bin/env bash
# Builds the markdown body for the tracking issue.
# Usage: build-issue-body.sh <gaps_path> <screenshots_path>
# Reads env: RUN_URL, COMMIT_SHA, RUN_TIMESTAMP
# Outputs: full markdown body to stdout.
set -euo pipefail

gaps_path="${1:-}"
shots_path="${2:-}"

cat <<EOF
> Generated by [find-the-gaps]($RUN_URL) at $RUN_TIMESTAMP for commit \`$COMMIT_SHA\`.

EOF

if [[ -f "$gaps_path" ]]; then
  cat "$gaps_path"
fi

if [[ -f "$shots_path" ]]; then
  echo
  echo "## Screenshot Gaps"
  echo
  cat "$shots_path"
fi
